### ISSUE TITLE
Failure handling image format

### ISSUE THREAD

**Issue by dwarning** [lxi-tools/lxi-tools#60]
Last time I used lxi-tools was about 6 month ago. Now it seems a new version automatically installed - version 2.3. Ubuntu 22.04 LTS 64bit.
If I want grep a screenshot I got this message above in the title. 

Connection seems OK:
`[192.168.178.42] :SYSTem:VERSion?
[192.168.178.42] 1999.0
[192.168.178.42] *IDN?
[192.168.178.42] Siglent Technologies,SDS1204X-E,SDSMMEBX3R3445,8.2.6.1.37R8
`

**Comment by lundmar** [comment]
I assume you are using the snap installed version of lxi-tools?

Could you try start lxi-gui from a terminal, it may write a more detailed error message there.

Also, please try retrieve the screenshot via the commandline tool: `lxi screenshot -a <device ip>` to see if that triggers a different response.

Maybe also try make sure you are running latest firmware on your scope, just in case there is a regression prevent the screenshot feature from working.

**Comment by dwarning** [comment]
Martin,

thanks for your quick reply.

That comes from start and grep one image:


***@***.***:~/Projects/MicronetToNMEA$ lxi-gui
Gsk-Message: 14:48:22.494: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Toplevel': Failed to create EGL display

Gsk-Message: 14:48:23.155: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Popup': Failed to create EGL display


(lxi-gui:58690): GdkPixbuf-CRITICAL **: 14:48:55.274: 
gdk_pixbuf_loader_write: assertion 'GDK_IS_PIXBUF_LOADER (loader)' failed

(lxi-gui:58690): GdkPixbuf-CRITICAL **: 14:48:55.274: 
gdk_pixbuf_loader_get_pixbuf: assertion 'GDK_IS_PIXBUF_LOADER (loader)' 
failed


Perhaps it helps,

Dietmar

Am 06.11.22 um 13:05 schrieb Martin Lund:

**Comment by lundmar** [comment]
Ahh, I see now. It looks like the new snap is missing the image loader plugins which are required for handling some image formats. I'll see if I can update the snap to fix it.

**Comment by lundmar** [comment]
If you are on an amd64 architecture and you switch to the snap edge channel it should work now.

Do `snap refresh lxi-tools --edge` to switch to the edge channel version.

**Comment by dwarning** [comment]
I made the refresh:
`snap refresh lxi-tools --edge
lxi-tools (edge) 2.4 von Martin Lund (lundmar) aufgefrischt`

But problem still exist. Same writeout in console.

**Comment by lundmar** [comment]
Are you running lxi-tools on a PC or perhaps an ARM system?

**Comment by dwarning** [comment]
It is an old HP laptop with Ubuntu 22.04 LTS.

After reboot, still the same.

How I can see the build number?

Am 06.11.22 um 16:09 schrieb Martin Lund:

**Comment by lundmar** [comment]
To see build number try `snap info lxi-tools`.

**Comment by dwarning** [comment]
I got this:

***@***.***:~$ snap info lxi-tools
name:      lxi-tools
summary:   Open source LXI tools
publisher: Martin Lund (lundmar)
store-url: https://snapcraft.io/lxi-tools
license:   unset
description: |
   Lxi-tools are open source software tools for managing LXI compatible test
   instruments such as modern oscilloscopes, power supplies, spectrum
   analyzers etc.
   Features include automatic discovery of test instruments, sending SCPI
   commands, grabbing screenshots from supported instruments, benchmarking
   SCPI message performance, and powerful scripting for test automation. 
Both
   a commandline tool and a GUI application are available.
commands:
   - lxi-tools.lxi
   - lxi-tools.lxi-gui
snap-id:      yha3V4dqfwJwpjSWgMFEMViAlQ2iMdL7
tracking:     latest/edge
refresh-date: heute um 15:47 CET
channels:
   latest/stable:    2.3 2022-10-29 (1563) 35MB -
   latest/candidate: 2.3 2022-10-29 (1563) 35MB -
   latest/beta:      2.3 2022-10-29 (1563) 35MB -
   latest/edge:      2.4 2022-11-06 (1568) 35MB -
installed:          2.4            (1568) 35MB -


Am 06.11.22 um 16:23 schrieb Martin Lund:
> |snap info lxi-tools|

**Comment by lundmar** [comment]
Ok, looks like you are on the right build number. I'll do some more debugging on the edge channel.

**Comment by dwarning** [comment]
Thanks,
I made experiments with wayland and xorg server, but no difference.

**Comment by lundmar** [comment]
Please try build 1572 on the edge channel. It should finally fix the issue.

**Comment by dwarning** [comment]
Sorry Martin, its still the same. See my console, which is now different:

***@***.***:~/Projects/MicronetToNMEA$ snap info lxi-tools
name:      lxi-tools
summary:   Open source LXI tools
publisher: Martin Lund (lundmar)
store-url: https://snapcraft.io/lxi-tools
license:   unset
description: |
   Lxi-tools are open source software tools for managing LXI compatible
   test instruments such as modern oscilloscopes, power supplies,
   spectrum analyzers etc.
   Features include automatic discovery of test instruments, sending
   SCPI commands, grabbing screenshots from supported instruments,
   benchmarking SCPI message performance, and powerful scripting for
   test automation. Both a commandline tool and a GUI application are
   available.
commands:
   - lxi-tools.lxi
   - lxi-tools.lxi-gui
snap-id:      yha3V4dqfwJwpjSWgMFEMViAlQ2iMdL7
tracking:     latest/edge
refresh-date: heute um 21:48 CET
channels:
   latest/stable:    2.3 2022-10-29 (1563) 35MB -
   latest/candidate: 2.3 2022-10-29 (1563) 35MB -
   latest/beta:      2.3 2022-10-29 (1563) 35MB -
   latest/edge:      2.4 2022-11-06 (1572) 35MB -
installed:          2.4            (1572) 35MB -
***@***.***:~/Projects/MicronetToNMEA$ lxi-gui
Gsk-Message: 21:50:18.341: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Toplevel': Failed to create EGL display

Gsk-Message: 21:50:18.979: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Popup': Failed to create EGL display

Supported GDK Pixbuf formats:
png
jpeg
ani
bmp
gif
icns
ico
pnm
qtif
tga
tiff
xbm
xpm

(lxi-gui:21407): GdkPixbuf-CRITICAL **: 21:50:47.220: 
gdk_pixbuf_loader_write: assertion 'GDK_IS_PIXBUF_LOADER (loader)' failed

(lxi-gui:21407): GdkPixbuf-CRITICAL **: 21:50:47.220: 
gdk_pixbuf_loader_get_pixbuf: assertion 'GDK_IS_PIXBUF_LOADER (loader)' 
failed


Perhaps I have to install dedicted libraries.


Am 06.11.22 um 21:03 schrieb Martin Lund:

**Comment by lundmar** [comment]
Hmm, that is puzzling. I have fixed so that the gdk pixbuf loader is finally loading support for bmp as you can see in the supported format list. Before it was only supported png and jpg.
Also, all required libraries are shipped in the snap.

For scopes that produce png or jpg everything works fine. I'll have to dig deeper tomorrow to figure out why bmp is still not working.

**Comment by dwarning** [comment]
The goal is to produce png's, not bmp. This has worked with the former versions very well.
It is SDS 1204-X-E with latest firmware. Normally I got png's.

**Comment by lundmar** [comment]
Ok, I've digged a bit deeper and applied some more fixes. Please try latest build 1577 on the edge channel. Thanks.

**Comment by dwarning** [comment]
OK Martin, know it is OK. Good work.

Thank you,

Dietmar

BTW - I get still these stupid gdk / gsk messages, but all my 
engineering programms throughing this out:

***@***.***:~/Projects/MicronetToNMEA$ lxi-gui
Gsk-Message: 17:00:08.688: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Toplevel': Failed to create EGL display

Gsk-Message: 17:00:09.434: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Popup': Failed to create EGL display


(lxi-gui:53176): GLib-GIO-WARNING **: 17:01:12.606: Error creating IO 
channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Gsk-Message: 17:01:12.663: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Toplevel': Failed to create EGL display

Gsk-Message: 17:01:12.786: Failed to realize renderer of type 
'GskGLRenderer' for surface 'GdkX11Popup': Failed to create EGL display

Am 07.11.22 um 16:46 schrieb Martin Lund:

**Comment by lundmar** [comment]
Great, thank you for reporting the issue.

You can ignore the error messages, they are not as fatal as they appear.

**Comment by lundmar** [comment]
FYI - I've upgraded the stable channel with the new fix.
